language: php

php:
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install: composer install --prefer-source $COMPOSER_FLAGS

script: ./vendor/bin/phpunit --coverage-text